### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by ToothyDev** [ZaharX97/OWReveal#10]
Whenever I change any of the settings, they don't stay saved when I exist and reopen OWRevealer. They are saved during the current runtime, but not after it closed. There's also no settings file, if there's supposed to be one

**Comment by ZaharX97** [comment]
You have to press the bottom right button, "Save to file", otherwise a settings file won't be created.

**Comment by ToothyDev** [comment]
There is no button saying that in the settings tab for me

**Comment by ZaharX97** [comment]
can you give a screenshot? 
![image](https://user-images.githubusercontent.com/23224202/122681910-433f0000-d1ff-11eb-9e03-0ff5be09724d.png)

**Comment by ToothyDev** [comment]
I realized that overriding the DPI scaling behaviour to make the app not blurry makes the buttons disappear, for some reason. Disabling it showed them.

**Comment by ZaharX97** [comment]
What's your monitor resolution? I'm curious why it looks blurry to you

**Comment by ToothyDev** [comment]
Usual 1920x1080 but I use a 125% scaling because for some reason connecting my laptop to my screen sizes everything down 25%, so I do that to equalize it
