### ISSUE TITLE
Scaling causes issues all over the app

### ISSUE THREAD

**Issue by ToothyDev** [ZaharX97/OWReveal#11]
![image](https://user-images.githubusercontent.com/55001472/122906690-b86f1a00-d352-11eb-936e-3d7acb1cb9f1.png)

1920x1080 resolution
125% scaling
Settings buttons disappear, in the screenshot above you can see that the tenth player in the watchlist doesn't display
Info: I'm running this (below) to remove blur
![image](https://user-images.githubusercontent.com/55001472/122906899-ebb1a900-d352-11eb-9e90-a28b2a338c15.png)

**Comment by ZaharX97** [comment]
I'm not sure how to fix this from within the app :D
Does ticking this box help with the issue?
![image](https://user-images.githubusercontent.com/23224202/123524294-ec8b6780-d6d1-11eb-8824-ab2c80fd5ad0.png)

**Comment by ToothyDev** [comment]
Yes, I did, but it didnt help sadly :/

**Comment by ZaharX97** [comment]
ok, can you try the new version?
save your settings again and edit the ow_config > scaling > put your windows scaling there

**Comment by ToothyDev** [comment]
Yup, that works now!
![image](https://user-images.githubusercontent.com/55001472/123792965-837a3e80-d8e1-11eb-95ec-c32aec75ebb6.png)
text is a lil small but that will be fine, at least I can see all buttons now!

**Comment by ZaharX97** [comment]
hmm, from what i could test they should be normal sized :(
the dpi properties looks like this right? top box unchecked, bottom checked to application?
![image](https://user-images.githubusercontent.com/23224202/123793502-701fa100-d8ea-11eb-8605-8683f2632e41.png)

**Comment by ToothyDev** [comment]
Yup, I have it set to exactly that on my side
![image](https://user-images.githubusercontent.com/55001472/123793858-7f9aec00-d8e2-11eb-9aa1-2ab49c19fa4d.png)
![image](https://user-images.githubusercontent.com/55001472/123793883-845fa000-d8e2-11eb-813f-c4e1ea9566ec.png)
![image](https://user-images.githubusercontent.com/55001472/123793921-8f1a3500-d8e2-11eb-8940-4d959edb3ea0.png)

**Comment by ZaharX97** [comment]
i hoped it would be fixed automatically :D
maybe you can try to use another scaling value ( probably between 100 and 125 ) to make the buttons bigger

**Comment by ToothyDev** [comment]
Yes I tried that too and managed to get a good result with it :) thanks

**Comment by ZaharX97** [comment]
cool
