### ISSUE TITLE
Suggestion: Add option to copy users Steam64 ID

### ISSUE THREAD

**Issue by notcreeperdude** [ZaharX97/OWReveal#14]
I just think it would be useful as i use another tool that analyzes the case, ranks the user in categories such as aimbot and wallhack and stores it to a file. But it used the steam64 ID and it's a pain for me to click the profile then use an ID grabber if they have a custom URL.

**Comment by ZaharX97** [comment]
so when you have a demo, do you need only the steam64 of the suspect or of all people?
also can u link the other program?

**Comment by notcreeperdude** [comment]
Here's the git for the other program. https://github.com/BeepIsla/CSGO-Overwatch-Bot. Its can be used to fully automate overwatch cases but as i use it it just scores them and stores results. Also it only needs the steamID of the suspect but im sure a function thatss run for each playerr and just grabs them all would suffice.

**Comment by ZaharX97** [comment]
so i guess it would be ok if you right click on a name to copy the steamid64, right?

**Comment by notcreeperdude** [comment]
that would be absolutely perfect

**Comment by notcreeperdude** [comment]
Also question while we are active in this thread, am i abble to add date/time to the end of a replay name?

**Comment by ZaharX97** [comment]
i might be able to add date and time when u download it
