### ISSUE TITLE
Teams shown incorrectly?

### ISSUE THREAD

**Issue by ToothyDev** [ZaharX97/OWReveal#16]
Today I did an Overwatch case and was confused as I couldn't seem to find out who the suspect was
I then looked at the opposing team, and sure enough, the stats matched (screenshots below)
![image](https://user-images.githubusercontent.com/55001472/123516335-d6fb4b00-d69b-11eb-8bea-676416bc29ba.png)
![image](https://user-images.githubusercontent.com/55001472/123516347-e5496700-d69b-11eb-8da9-2a115ac05488.png)
As you can see, the teams in OWRevealer seem to be mixed up - I didn't have this until now so I was quite confused when I realized

**Comment by ZaharX97** [comment]
Do you have the demo? Or the overwatch link?

**Comment by ToothyDev** [comment]
Sadly I don't anymore, but I think I might know what the problem is
As you can see, the round played is the 16th, meaning after the team switch.
What I think happens is that OWRevealer thinks we are still basically at the end of round 15, thus with the suspect still in the CT team. I will say that yes, it's confusing to make it correct given there is no real point in time where it's "12:3", it could be both at the end of round 15 or at the start / during round 16. My tip, if not already implemented like that, would be to always take a round's starting results to display

**Comment by ZaharX97** [comment]
Oh I see, I thought it's another bug.
It was like this from the first day, all stats are the stats from the end of each round.
It's this way so the first round doesnt show 0/0/0 for all, also for stats at the end of the match.
It's a bit confusing at half time but if you think of it as "end of round X stats" it makes sense (to me at least :) )
