### ISSUE TITLE
[REQUEST] New Site Addition

### ISSUE THREAD

**Issue by lilgandhi1199** [ZaharX97/OWReveal#17]
https://zahar.one/owrev
Your new site is amazing!
I have always dreamed of someone doing this to track replays that I was maybe involved in.
https://steamcommunity.com/profiles/76561197997327350

That's my profile. I have done a ton of coding and download every single replay file and eventually parse out statistics and tag every involved players steamIDs.

My request is if you could also add a way to grab the direct replay file link!
http://replay118.valve.net/730/003489539285936242722_0621905606.dem.bz2

We could watch the banned players (which I see you are scanning their profiles for bans and marking them red :D)
Or just if we ever see our own steamIDs in there we could DL to see what they saw.

**Comment by ZaharX97** [comment]
It wouldn't be hard to add this, but most of the demos are spinbots and I'm not sure if valve would like this ideea so I wont make links public :D

**Comment by lilgandhi1199** [comment]
Well automating overwatch submissions is far worse than making demos public.
I just want to look at some losers with high hours get banned. :D
