### ISSUE TITLE
Broken Setting (Auto start )

### ISSUE THREAD

**Issue by Ancient77** [ZaharX97/OWReveal#18]
The Setting "Auto start scanning when opening the app" doesn't make any sense since the program is not saving the connection you want to look for packets. For me every time I start with the setting on it just gives me an error.

**Comment by ZaharX97** [comment]
After you do your settings, press the save button in the bottom right corner. (I'll rename it later to save settings)
The connection is saved after you start searching, then if you save your settings it will always be there

**Comment by Ancient77** [comment]
But Can I somehow save the connection I want to look for packets? Otherwise, it's just gonna tell me I have to choose one after I start the program. It seems like it doesn't save my connection at all.

**Comment by ZaharX97** [comment]
Yes, select your connection, press start, then go to settings and save

**Comment by Ancient77** [comment]
Oh, I think the problem was that I choose the connection "None". If this is intended you can close this issue.

**Comment by ZaharX97** [comment]
Oh, that's a bug. I'll work on it tomorrow

**Comment by ZaharX97** [comment]
should be fixed
