### ISSUE TITLE
Can't build an exe?

### ISSUE THREAD

**Issue by ToothyDev** [ZaharX97/OWReveal#19]
I'm running Python 3.8.1, pyinstaller is installed of course, and I ran the command you provided in the readme. However...

![image](https://user-images.githubusercontent.com/55001472/124160592-b4eb3980-da9c-11eb-8143-ba722a6c5d6c.png)

Everything seems to have worked, but the exe is smaller than the one in the GitHub releases and it throws this error when running, what's the issue here?

**Comment by ToothyDev** [comment]
Edit: I thought I found the issue as I was missing modules so I installed them, however I was running into this issue
![image](https://user-images.githubusercontent.com/55001472/124161502-c5e87a80-da9d-11eb-892e-6ecb1ccdd0d0.png)

**Comment by ZaharX97** [comment]
~~i think you need the protobuf package not the google package~~
nvm, i see that you fixed the first issue

**Comment by ZaharX97** [comment]
try to replace get_windows_if_list with get_if_list
I also updated all packages and got that error :D

**Comment by ZaharX97** [comment]
the old function didnt exist anymore in scapy (or i couldnt find it) so I updated the code
