### ISSUE TITLE
Suggestion: Notification for duplicate steam64 id's

### ISSUE THREAD

**Issue by itsmepuffd** [ZaharX97/OWReveal#20]
I've encountered a couple of cases today with the same suspect from an earlier case I had registered. 

I can't add these to the watchlist, I would guess because it detects the steam64 id is already on the list even though this is a different map and such. Took me a little while to figure out why it was not adding to the watchlist. 

A small pop-up with previous entry # letting you know suspect is already on the list.

Thanks !

**Comment by ZaharX97** [comment]
added
