### ISSUE TITLE
Virustotal detection

### ISSUE THREAD

**Issue by Ancient77** [ZaharX97/OWReveal#21]
Hey, just wondering if you could do something about the Virustotal detections? I have no idea if they are false positives or not. 
https://www.virustotal.com/gui/file/313d6d5cbfb07858e39d1e84df5dc38f3c831ee9d17849805d5934d961db676c/detection

**Comment by ZaharX97** [comment]
I recently updated pyinstaller (the one that creates the exe) and from 2 detections now there's 4.
I'll use the old version later today, meanwhile you can use the [v4.5 release](https://github.com/ZaharX97/OWReveal/releases/tag/4.5)

**Comment by ZaharX97** [comment]
Done, I updated the [latest release](https://github.com/ZaharX97/OWReveal/releases/tag/4.5.2) with new exes. Back to only 2/68.
