### ISSUE TITLE
Fatat error detected

### ISSUE THREAD

**Issue by menubboi** [ZaharX97/OWReveal#22]
![image](https://user-images.githubusercontent.com/69341077/124818395-9bf4f380-df88-11eb-9b61-3da806a02478.png)
I'm having this issue while using latest version of owreveal [v4.5.2]

**Comment by ZaharX97** [comment]
So you didnt have this before? Someone had this problem before [(here)](https://github.com/ZaharX97/OWReveal/issues/7) and it was because of Norton antivirus

**Comment by menubboi** [comment]
No , I didn't have this problem before , 
I m not using norton antivirus but i don't think its related .
I have tried version v[4.3.3,4.2.4,4.3.6] without any issue and 
they all still work fine

**Comment by ZaharX97** [comment]
Can you try the version with the console and tell me if it shows another error?

**Comment by menubboi** [comment]
I tried running through console , It ran but it was sluggish and was not able to detect link maybe it was slow .
So maybe pyinstaller issue ?
It would be nice to have all the requirement text containing all the modules  for maybe future debugging purpose

**Comment by ZaharX97** [comment]
kinda late but i made a list :)
(scapy / requests / Pillow / mysql-connector)
