### ISSUE TITLE
No module named 'scapy'

### ISSUE THREAD

**Issue by RenaFor01** [ZaharX97/OWReveal#23]
I'm new to coding, idk if i've done anything wrong but I would like some help with this error please.

![1](https://user-images.githubusercontent.com/91011776/133925322-845a153f-4dfe-499b-908c-759892c777af.png)

**Comment by ZaharX97** [comment]
Sure!
In this project I used other libraries/modules (the ones that are imported at the top of the files).
Some are built into python, but there are some that are not. So you need to add them to your python interpreter.
You can do this by using ' pip '.
Open a cmd/terminal and type: ' pip install xxxxxxx ' (replace xxx with module name)

Here's the list of modules you need for this project:
- scapy
- requests
- Pillow
- mysql-connector
- pyinstaller (this is extra, you dont need this if you run the project from python, only if you wanna create a standalone .exe)

**Comment by RenaFor01** [comment]
It works now, thank you!
