### ISSUE TITLE
CSGO Rank Not Revealed

### ISSUE THREAD

**Issue by franklinworm** [ZaharX97/OWReveal#28]
App is working fine.But, Rank revealer not work do you have solution for it?
![Screenshot_10](https://user-images.githubusercontent.com/68368765/136116967-9b42a06b-e726-44fb-9e4b-61f159002e1f.png)

**Comment by ZaharX97** [comment]
Probably just an unranked game.
I'll check it later

**Comment by franklinworm** [comment]
Yes,i ts unranked, how to connect steam api key into this app?

**Comment by ZaharX97** [comment]
Go to settings, click on the "api key" text.
It will open steam in your browser.
Copy your api key and paste it in settings.
Finally, save your settings

**Comment by franklinworm** [comment]
What should i name it for domain?

**Comment by ZaharX97** [comment]
Anything u want

**Comment by franklinworm** [comment]
What is the steam api key function

**Comment by ZaharX97** [comment]
If you check for new bans in watchlist, it will use a different function to search faster by making calls to steam api.

**Comment by franklinworm** [comment]
![API](https://user-images.githubusercontent.com/68368765/136207106-6019c7b7-fdb8-4dec-91e6-16f80245c257.png)
Error appears when use api key

**Comment by franklinworm** [comment]
Problem Solved
