### ISSUE TITLE
it doesn't work now

### ISSUE THREAD

**Issue by JMmumu** [ZaharX97/OWReveal#3]
I can't reveal any ow demo...

**Comment by ZaharX97** [comment]
Still works for me. Did you install npcap or wireshark?

**Comment by JMmumu** [comment]
thanks for reply
I installed npcap and it worked at yesterday,but today I can't use it. Maybe the perfectworld server problem.
I will test again.

**Comment by JMmumu** [comment]
Problem solved. I'm in China,the download source is “replay.csgo.com.cn”,not same as worldwide game. I change my IP and it works.
