### ISSUE TITLE
[Request] Suspect ID, auto add watchlist, csgo-overwatch-bot, auto remove after X days.

### ISSUE THREAD

**Issue by Ativ3k** [ZaharX97/OWReveal#30]
Show suspect id and auto add to watchlist.
Or maybe auto add to watchlist if [csgo-overwatch-bot](https://github.com/BeepIsla/CSGO-Overwatch-Bot) gives a positive verdict.

Auto remove from watchlist older than X days without ban. ( x => 1 if 0 = dont remove. But on website auto remove after 30 days.)

**Comment by ZaharX97** [comment]
Forgot to respond to this one.
I don't want to automate overwatch, valve could do this itself.
About the auto remove, if the list will be too big and will take too much time to load, i will make it auto delete.
