### ISSUE TITLE
[REQUEST]Add mode to OWRevealer

### ISSUE THREAD

**Issue by MystikReasons** [ZaharX97/OWReveal#31]
It would be nice to know if the game is a ranked or an unranked since you list it on your website but not in the OWReveal itself.
Would that be possible?

**Comment by MystikReasons** [comment]
Completely forgot that non prime player can not play ranked.

**Comment by ZaharX97** [comment]
Thats true 😆 
But anyway, the demos don't show if it's a ranked or unranked game (or at least i couldnt find a 100% certain way).
The way i do it is like this: if rank is shown for any (even one) player -> its a ranked game / otherwise it's unranked
