### ISSUE TITLE
[Suggestion] - Ability to add steam profile link for watch list

### ISSUE THREAD

**Issue by suhasholla** [ZaharX97/OWReveal#38]
Can you please try to add  the ability to add steam profile link for watch list. Suppose if we have the steam profile and put it to watch list

**Comment by ZaharX97** [comment]
This app also adds some other data when you add player from a demo (map, k/d/a, rank...)
If you really want to add a player and dont care about the other data:
- go to the folder where you have this app
- use notepad to open 'watchlist'
- copy the whole last row and duplicate it
- change the first numbers to the player steamid
- change the player name (between k/d/a and map name)
- save, thats it

If you have the demo you can open settings and click 'analyze demo', then you can add as normal

**Comment by suhasholla** [comment]
Thanks. Much appreciated !!
