### ISSUE TITLE
[Discussion] What about PyQt and website api?

### ISSUE THREAD

**Issue by NoPlagiarism** [ZaharX97/OWReveal#39]
Were you thinking about rework all application to PyQt6? I can help with it
Also what about website api?
It could be used also for detecting if players were in db before

**Comment by skhrlx** [comment]
A web UI is good too 🙂 for example, when you are over overwatching on your PC, you can open all the things up on your phone browser and check the steam, or whatever you need to do

**Comment by NoPlagiarism** [comment]
So what about api? It would be good, if you could check all player profiles in demo with one request

**Comment by NoPlagiarism** [comment]
And also, you haven't said anything about PyQt6
P.S: Because rework on PyQt6 means a lot of rework with code, so I need an opinion

**Comment by ZaharX97** [comment]
It's too much work to rewrite to pyqt and i dont see the benefit
About the website api, it's not something too developed but you can add /s/steamid to get some json data (the last element [11]  is the number of times the player was added to db)

**Comment by NoPlagiarism** [comment]
I know about /s/, but I'm talking about request to find data of multiple ids

**Comment by NoPlagiarism** [comment]
Also, I suggest to open discussions in repository

**Comment by ZaharX97** [comment]
discussions? is that something new in github?

**Comment by NoPlagiarism** [comment]
> discussions? is that something new in github?

[Yep. You can read about it here](https://resources.github.com/devops/process/planning/discussions/) 
For example, this issue can be transferred to there.

**Comment by NoPlagiarism** [comment]
- [Discussions](https://github.com/features/discussions): should be started
-  PyQt remake: maybe I'll do it as OwRev fork somewhen
- Website: disabled from #45
