### ISSUE TITLE
Check Vacban not working

### ISSUE THREAD

**Issue by Flashbert** [ZaharX97/OWReveal#4]
Check Vacban is not working (i'm from Germany), so i suppose it's because he receive the website in my local language and can't find the "bans on record" string.

I think if you check the profile with ?l=english at the end it would work for every country.

Example: https://steamcommunity.com/profiles/76561198814754956?l=english

**Comment by ZaharX97** [comment]
nice bug

I put out a new version, if it doesnt work let me know :)

**Comment by Flashbert** [comment]
Maybe it wasn't the problem tho, still not working.

not sure if this "error"-title is normal. After that window it says 0 new bans.

![grafik](https://user-images.githubusercontent.com/15714048/115025930-31b93f00-9ec2-11eb-96ec-accb626d6ee2.png)

**Comment by ZaharX97** [comment]
Can you upload your watchlist file? Maybe nobody really got banned

The error title is normal, i forgot to change it

**Comment by Flashbert** [comment]
the guy from the example is in the list:
76561199132419289 N 16-Apr-2021 08:36:20 5=boozt 11=57 / 10 / 2 8=de_dust2 2=14 7=EU East 1=6
76561199147441743 N 16-Apr-2021 10:37:04 6=MEEPOV 11=20 / 4 / 11 9=de_mirage 2=13 8=EU North 1=6
76561198814754956 N 16-Apr-2021 10:38:43 5=二次元刀酱 10=63 / 1 / 1 7=de_nuke 1=8 4=Asia 1=6

**Comment by ZaharX97** [comment]
I think I know what happened.

The guy in the list already has a game ban from 193 days ago, but you found him in overwatch recently. This means that he's not vac banned in CSGO but in another game.

My program checks if people were banned after you added them to watchlist.
