### ISSUE TITLE
application freeze

### ISSUE THREAD

**Issue by wizzz3** [ZaharX97/OWReveal#40]
the app freezes after i press the "start" button, what could it be?

**Comment by ZaharX97** [comment]
probably the app didnt find any network connections
did you restart the pc after installing npcap?

alternatively if you are having this problem on mac os i can't attempt and test any fixes

**Comment by wizzz3** [comment]
i have installed/reinstalled npcap and restarded my pc every time i installed it.
i believe this started happening after one of the windows updates because the app used to work on my computer a few months ago but i am not sure if this is the case, and yeah... i am on windows 10 21H1 19043.1645
i also tried disabling the firewall, but the crashing still persists

npcap is running
C:\Windows\system32>sc query npcap

SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by NoPlagiarism** [comment]
Have you tried catch something in WireShark? Maybe we need to find problem in npcap itself

**Comment by wizzz3** [comment]
yes, i have installed wireshark and it captures my network data just fine.
i have the latest npcap version installed (1.71)

**Comment by NoPlagiarism** [comment]
@wizzz3 So, what was the problem?

**Comment by wizzz3** [comment]
i honestly don't know, i uninstalled betternet (a vpn that i was not running at all), uninstalled gamersclub anticheat, faceit anticheat, win scp, wireshark, basically went on a uninstall spree and now it works
