### ISSUE TITLE
New row messes up the layout

### ISSUE THREAD

**Issue by hurdurderp** [ZaharX97/OWReveal#41]
Hello,
that's not a real bug of OWReveal, hope it's still okay that I open an issue.
I tried to implement some new things but when i add a new row in the settings menu the window size is wrong and the last row is hidden until I manually adjust the window size. Tried to lookup how you did it in the updates.

Expected:
![owreveal_settings_menu_expected](https://user-images.githubusercontent.com/27501522/199388924-4f45da5e-c32f-45b3-9d90-811ab78bff4c.png)
Currently:
![owreveal_settings_menu_currently](https://user-images.githubusercontent.com/27501522/199388923-33932df4-73de-4553-8346-4a635dfb1162.png)

Played with window.minsize but with no success, last row is always hidden.
With window.minsize(580, 475) you can see a tiny bit of the last row. 

My current code
https://github.com/hurdurderp/OWReveal/commit/64d0c8ea0e74aad0cf6ce2488d55a83654fc5f19

Ty

**Comment by ZaharX97** [comment]
sorry for late response,

now that you added 1 more row, there are 13 totals
so you wanna also change the minsize they occupy from the window
before it was 100%/12 rows = 0.083 minsize
now its 100%/13 rows = 0.076 minsize
lines 227-239 in settingswindow.py
