### ISSUE TITLE
Doesn't work in Wi-Fi

### ISSUE THREAD

**Issue by mapperxray** [ZaharX97/OWReveal#43]
I use laptop and when i try to start looking for demo from Wi-Fi the program just stops responding and crashes. It is fine as long as i use LAN Cable and search in Ethernet, is there a way to make it work in Wi-Fi please?

EDIT: Select none if not sure is also crashing.

**Comment by NoPlagiarism** [comment]
You can try choosing your network adapter

**Comment by mapperxray** [comment]
> You can try choosing your network adapter

How?

**Comment by NoPlagiarism** [comment]
> How?
### Here?
![Um...](https://user-images.githubusercontent.com/37241775/208744115-4d1a6836-1b9b-408b-bb81-8714b73f23cf.png)

**Comment by mapperxray** [comment]
Ethernet 2 does not show up besides all of the things on the list is not working and making it crash

**Comment by NoPlagiarism** [comment]
`Ethernet 2`? Why you are so sure about it? Maybe it's some wireless connection?

Like `Wi-Fi` or sth else?

**Comment by mapperxray** [comment]
![Here,](https://user-images.githubusercontent.com/74987176/208865740-a41f392f-1e05-4603-9e6d-148d56cdfec1.png)

These are all the things that show up and all of them are crashing.

The translation for the ones called "Yerel Ağ Bağlantısı" are "Local area network"

As i previously mentioned i use Laptop with Wi-Fi and Ethernet works well as long as i use LAN Cable but sometimes i'm unable to use LAN Cable so i wanna use the program with Wi-Fi but none of the options work besides using LAN Cable so this is why i want help on this.

**Comment by mapperxray** [comment]
I've messed with my network settings and somehow it started working.
