### ISSUE TITLE
Idea: Log ban date / ban speed

### ISSUE THREAD

**Issue by Flashbert** [ZaharX97/OWReveal#5]
Log ban date, or if not possible log date when you manually check and maybe show calculated banspeed.

**Comment by ZaharX97** [comment]
Unfortunately valve doesnt make the ban date public, I can only approximate it.  
What do you mean by banspeed? How long it took for the player to get banned after you found him in OverWatch?

**Comment by Flashbert** [comment]
With banspeed i mean the time between overwatch case and vac/ow ban on his account.
Same i mean with ban date: record the date of vac/ow listed on his account. It could be another game but i think 95% it's csgo if you got him on ow AND he didnt have VAC before.

**Comment by ZaharX97** [comment]
The program is already doing that. I save the date when you find players in ow.
And then I check the last ban on his account. If the ban date is later then ow date, it probably is a csgo ban and I mark him with red in watchlist

**Comment by Flashbert** [comment]
yeah, i thought about something like that (convars.com), but not for your games but for OW:
![grafik](https://user-images.githubusercontent.com/15714048/117923179-e55ff400-b2f3-11eb-8596-9c7c67de0b99.png)

So you see how fast they get banned after your OW case

**Comment by ZaharX97** [comment]
Oh i see. I'll have to think how to add this without making the window bigger

**Comment by MystikReasons** [comment]
If I can come back to the Log ban date:
With your new release of the https://zahar.one/owrev website, wouldn't it be possible to program a crawler that checks every steam profile everyday for about 2-3 weeks for a VAC or a game ban and then display it on the website?

**Comment by ZaharX97** [comment]
Added this in v4.4
