### ISSUE TITLE
Player stats not showing

### ISSUE THREAD

**Issue by hurdurderp** [ZaharX97/OWReveal#6]
Hello,
today I got a demo who bugged out.
I get the map, server location, round count and kill feed but nothing more.
The player stats are missing.
Demofile https://www.mediafire.com/file/i780dpy3avd2fsm/totally_not_a_overwatch_demo.dem/file
Edit:
Another one 
https://www.mediafire.com/file/53t8dycxqr8udzf/003479959378562384023_2142826864.dem/file

**Comment by ZaharX97** [comment]
Thanks for writing about the bug. It's weird that games started with less than 10 players.  
I added a new version, I think it should be fixed
