### ISSUE TITLE
weird problem

### ISSUE THREAD

**Issue by 17kata** [ZaharX97/OWReveal#7]
![Untitled](https://user-images.githubusercontent.com/84897746/119780394-6e6d5280-bed2-11eb-918a-81effb13ba17.png)

**Comment by ZaharX97** [comment]
thats weird..
can you try to download the program again? or try the previous version?

**Comment by 17kata** [comment]
yep
i have try with the previus version, same error

**Comment by ZaharX97** [comment]
i think it might be from the icons but i'm not sure since i cant reproduce this on any computer...
can you also try [this version (4.1.2)](https://github.com/ZaharX97/OWReveal/releases/tag/4.1.2) that doesn't have icons?

**Comment by 17kata** [comment]
ehh,ehh.. the same

i have try to unistall my antivirus software also, but not.. i got the same error ;////

**Comment by ZaharX97** [comment]
maybe pyinstaller (the program that makes all files in one .exe) just doesn't work on your pc?
if you have python installed try to clone this repo and start main.py
or if you dont have python use the zip that i attached and start OWRevealer2.exe
[OwRevealer2.zip](https://github.com/ZaharX97/OWReveal/files/6565331/OwRevealer2.zip)

**Comment by 17kata** [comment]
same and same

if you have discord, add me: 17th#7794

**Comment by 17kata** [comment]
i have reinstall my windows 10 and now everything works fine

maybe the previous antivirus, Norton blocked some parts of this program or somethin, can't confirm anything

Thank you!

**Comment by ZaharX97** [comment]
oh cool, i'm glad that you fixed it
