### ISSUE TITLE
Ability to use your own SteamAPI key to speed ban check up?

### ISSUE THREAD

**Issue by ToothyDev** [ZaharX97/OWReveal#8]
As of now, it searches 1 player / second (I have 2 people in my list, I don't know if it just gives the current speed or if it's capped at 1/s). Using our own SteamAPI key would allow for people to check their watchlist for bans faster, and not risk being rate-limited.

Also question not worth an issue; shouldn't it check for Overwatch (= game) bans instead of VAC bans? Or, even better, both? Or does it already do that

**Comment by ZaharX97** [comment]
I didn't see a way to get player bans from steam api. If it exists please let me know.
In the meantime, now you can change the delay between player checks.

About the ow bans, again, I dont think you can see which type of ban a player has, can you?

**Comment by ToothyDev** [comment]
There definitely is a way to get player bans over the API; but I never used it so I don't know how
And yes, you can see which bans a player has as well

**Comment by Flashbert** [comment]
> About the ow bans, again, I dont think you can see which type of ban a player has, can you?

IT says VAC Ban on the record or game ban on the record:

Example 1: https://steamcommunity.com/profiles/76561199108430625/
Example 2: https://steamcommunity.com/profiles/76561199127737369/

**Comment by ToothyDev** [comment]
I know, and Overwatch bans count as game bans. Thus I found it a bit confusing that the App said check VAC bans

**Comment by ZaharX97** [comment]
Ok, I found the steam api call, I'll add the option to use your steam key in the next version.
